### ISSUE TITLE
Code review by peers

### ISSUE THREAD

**Issue by acolombo1** [Gedewon/ConferencePage_C1#2]
Aldo: Kindly I don't think you should use an image inside your h1 tag. Your work is great but I think you could personalize the content as asked in the guidelines.
Olamarx: Kindly fix the picture at the footer of the about page as it is not rendering on my machine.

**Comment by gedewon** [comment]
@acolombo1   closed the issue in favor of image within h1 element , having the right alt attribute in img tag.please do refer this [link](https://ravichauhan.org/can-an-h1-tag-be-an-image-three-points-when-setting-images/) for more information. and the rest issue are addressed. Thank you !!!
